repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: ['--autofix']
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  # Python
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.252
    hooks:
      - id: ruff
        args: ['--show-source', '--fix', '--config', 'ruff.toml']
  # Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ['--write-changes',
               '--ignore-words=.pre-commit/codespell_words',
               '--exclude-file=.pre-commit/codespellignorelines']
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.2.0
    hooks:
      - id: cspell
  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
  # Markdown
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
    - id: markdownlint
