extend-select = [
  # Enabled by default
  # pyflakes
  # "F",
  # pycodestyle
  # "E",
  "W",
  # mccabe
  "C90",
  # isort
  "I",
  # pep8-naming
  "N",
  # pydocstyle
  "D",
  # pyupgrade
  "UP",
  # flake8-2020
  "YTT",
  # flake8-annotations
  "ANN",
  # flake8-bandit
  "S",
  # flake8-blind-except
  "BLE",
  # flake8-boolean-trap
  "FBT",
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-commas
  "COM",
  # flake8-comprehensions
  "C4",
  # flake8-datetimez
  "DTZ",
  # flake-debugger
  "T10",
  # flake8-django
  "DJ",
  # flake8-errmsg
  "EM",
  # flake8-executable
  "EXE",
  # lake8-implicit-str-concat
  "ISC",
  # lake8-import-conventions
  "ICN",
  # flake8-logging-format
  "G",
  # flake8-no-pep420
  "INP",
  # flake8-pie
  "PIE",
  # flake8-print
  "T20",
  # flake8-pyi
  "PYI",
  # flake8-pytest-style
  "PT",
  # flake8-quotes
  "Q",
  # flake8-raise
  "RSE",
  # flake8-return
  "RET",
  # flake8-self
  "SLF",
  # flake8-simplify
  "SIM",
  # flake8-tidy-imports
  "TID",
  # flake8-type-checking
  "TCH",
  # flake8-unused-arguments
  "ARG",
  # flake8-use-pathlib
  "PTH",
  # eradicate
  "ERA",
  # pandas-vet
  "PD",
  # pygrep-hooks
  "PGH",
  # Pylint
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  # tryceratops
  "TRY",
  # Ruff-specific rules
  "RUF",
]
# line-length = 88
ignore = ["E501"]
# G004: loggins-f-string
extend-ignore = ["ARG002", "ANN101", "G004"]
target-version = "py311"
[pydocstyle]
convention = "google"
